//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ltt_2210900130_de05.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class lttTask
    {
        public string lttTaskId { get; set; }
        public string lttTaskName { get; set; }
        public Nullable<int> lttTaskLevel { get; set; }
        public Nullable<System.DateTime> lttStartDate { get; set; }
        public Nullable<bool> lttTaskStatus { get; set; }
    }
}
