//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeTuanTinh_2210900130.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeTuanTinh_2210900130Entities1 : DbContext
    {
        public LeTuanTinh_2210900130Entities1()
            : base("name=LeTuanTinh_2210900130Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ltt_SACH> ltt_SACH { get; set; }
        public virtual DbSet<ltt_TAGGIA> ltt_TAGGIA { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
