//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeTuanTinh_2210900130.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ltt_TAGGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ltt_TAGGIA()
        {
            this.ltt_SACH = new HashSet<ltt_SACH>();
        }
    
        public string ltt_MaTG { get; set; }
        public string ltt_TenTG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ltt_SACH> ltt_SACH { get; set; }
    }
}
