//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeTuanTinh_2210900130.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ltt_SACH
    {
        public string ltt_MaSach { get; set; }
        public string ltt_TenSach { get; set; }
        public Nullable<int> ltt_SoTrang { get; set; }
        public Nullable<int> ltt_NamXB { get; set; }
        public string ltt_MaTG { get; set; }
        public Nullable<bool> ltt_TrangThai { get; set; }
    
        public virtual ltt_TAGGIA ltt_TAGGIA { get; set; }
    }
}
