//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeTuanTinh_2210900130.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string ltt_UserName { get; set; }
        public string ltt_Password { get; set; }
    }
}
