//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LttLesson09.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LttK22CNTLesson09DbEntities2 : DbContext
    {
        public LttK22CNTLesson09DbEntities2()
            : base("name=LttK22CNTLesson09DbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LttKhoa> LttKhoa { get; set; }
        public virtual DbSet<LttSinhVien> LttSinhVien { get; set; }
    }
}
