//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LttLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LttSinhVien
    {
        public string LttMaSV { get; set; }
        public string LttHoSV { get; set; }
        public string LttTenSV { get; set; }
        public Nullable<System.DateTime> LttNgaySinh { get; set; }
        public Nullable<bool> LttPhai { get; set; }
        public string LttPhone { get; set; }
        public string LttEmail { get; set; }
        public string LttMaKH { get; set; }
    
        public virtual LttKhoa LttKhoa { get; set; }
    }
}
