//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LttLesson11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LttTaiKhoan
    {
        public string LttId { get; set; }
        public string LttUserName { get; set; }
        public string LttFPassword { get; set; }
        public string LttFullName { get; set; }
        public Nullable<int> LttAge { get; set; }
        public string LttEmail { get; set; }
        public string LttPhone { get; set; }
        public Nullable<bool> LttStatus { get; set; }
    }
}
